---
title: "My little garden"
format:
  html:
    toc: true
    toc-depth: 3
    smooth-scroll: true
---

# 1.Garden maintenance

## Time order

### Jan:

冬肥，重剪，最冷的时候啥也不用干

### Feb:

冬肥，重剪，入春前扦插播种，最冷的时候啥也不用干

### Mar:

生长季，春季抹芽控型，小白药，小粉药，蜗牛药

### Apr:

生长季，春季抹芽控型，春肥，小白药，小粉药，蜗牛药

### May:

生长季，春肥，停止生长后轻剪，入梅前清理杂草，入梅前扦插

### Jun:

停止生长后轻剪，入梅前清理杂草,出梅后用刺蛾药（高效氯氰菊酯，半个月一次）

### Jul:

出梅后用刺蛾药（高效氯氰菊酯，半个月一次）

### Aug:

### Sep:

秋肥，小白药，小粉药

### Oct:

秋肥，小白药，小粉药，中剪，移栽，修根，入秋前扦插

### Nov:

扫落叶清理，中剪，移栽，修根，收集种子

### Dec:

扫落叶清理，然后开始清园喷药，最冷的时候啥也不用干

## Task order

### 施肥

冬天施肥，储存能量

春天开始生长后施肥激一下

秋天开始生长前施肥激一下，避开夏天高温

控量不要烧苗了

### 修剪

[枫树修剪-先养干后养冠](https://mp.weixin.qq.com/s/pLEQZ5Ab2TiQnpMi0QTeug)

集中在出冬后（看失枝情况），根据春季生长的加粗，长高的预期修剪，剪下的枝条刚好可以扦插准备春季的生长。

出夏后，入秋前，不至于剪枝受伤，又可以激发秋季再串一串，然后继续扦插

（春季入夏前那波可能不太适合，新枝条还太嫩，跟多是去掉一些叶子，减少夏天丢失水分的压力，也可能是我想的不对）

### 扦插

春季2-3月发芽前，9-10月秋季生长季前

修建后的枝条，底部去皮，杀菌，生根液泡一下，统一种植到育苗棚里

### 抹芽

春季3-4月发芽后，看一下生长情况，针对已经开始定型的树看一下新出的芽点，为了防止串枝，抹掉芽点

### 用药

如春后关注枝干上有没有蚜虫，一般小白药小粉药可以预防；

然后是入春时，入梅前，湿度大时容易滋生蜗牛，啃食植物叶片，可以撒点小蓝药防蜗牛；

然后是入夏时，入秋前，昆虫，飞蛾下卵开始出毛毛虫，天牛，需要用高效氯氰菊酯，半个月一次

### 清理

春季开始肆意生长，需要在入梅前清理杂草，保持清爽以免细菌，虫子滋生，同时做一次露台地面水道清理。

秋季落叶后把放了一年成熟自然掉落的种子收集一下，枯叶集中吹到一起，入冬前一次性清理掉，同时做一次露台地面水道清理，以及两个木台下面清理。

### 移栽

秋季落叶后，11-12月最适合移栽，修根（盆栽）；其次是5-6月，春季生长期后，开始

# 2. My little friends:

## 泰勒

## 金隐

## 月升

## 秋月

## 火烈鸟

## 蓝杉

。。。。

# 3. My little garden shop

## 土

## 盆

## 植物

## 太阳能灯

## 其它
